# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-25 06:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20160124_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 24, 23, 54, 56, 701900), verbose_name='date created'),
        ),
    ]
