# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-25 07:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_todolist_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 25, 0, 54, 3, 897477), verbose_name='date created'),
        ),
    ]
