# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-26 03:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_auto_20160125_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 25, 20, 34, 22, 173540), verbose_name='date created'),
        ),
    ]
