# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-26 05:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_auto_20160125_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 25, 22, 20, 14, 300327), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 25, 22, 20, 14, 300327), verbose_name='date created'),
        ),
    ]
