# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 16:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0018_auto_20160127_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 28, 9, 8, 11, 694717), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 28, 9, 8, 11, 694176), verbose_name='date created'),
        ),
    ]
